In [26]:
import pandas as pd
import numpy as np

In [27]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

## 데이터 탐색

In [28]:
print('train :', train.shape)
print('test :', test.shape)

train : (10000, 21)
test : (10000, 20)

In [29]:
train.head(2)

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit_Mix,...,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,56.0,16.0,11.0,35.598217,120.0,Yes,229.093478,252.385965,1,Bad,...,15.0,36597.56,8.0,10.0,29.0,5.0,3143.796667,22.49,2963.18,122.900223
1,49.0,23.0,12.0,25.553106,120.0,Yes,104.613906,219.105944,1,Bad,...,28.0,32057.30,9.0,8.0,16.0,7.0,2606.441667,1.40,1327.26,164.859426

In [30]:
test.head(2)

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,4.0,8.0,2.0,33.444469,239.0,No,104.467859,503.976904,Good,Low_spent_Small_value_payments,54.0,43754.32,5.0,7.0,7.0,1.0,3938.193333,7.55,515.73,35.374569
1,31.0,19.0,14.0,27.762143,93.0,Yes,149.137974,219.372773,Bad,High_spent_Small_value_payments,40.0,18836.23,6.0,8.0,16.0,6.0,1280.685833,14.26,1310.56,49.557837

In [31]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  object
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Score              10000 non-null  int64
 9   Credit_Mix                10000 non-null  object
 10  Payment_Behaviour         10000 non-null  object
 11  Age                       10000 non-null  float64
 12  Annual_Income             10000 non-null  float64
 13  Num_Bank_Accounts         10000 non-null  float64
 14  Num_Credit_Card           10000 non-null  float64
 15  Interest_Rate             10000 non-null  float64
 16  Num_of_Loan               10000 non-null  float64
 17  Monthly_Inhand_Salary     10000 non-null  float64
 18  Changed_Credit_Limit      10000 non-null  float64
 19  Outstanding_Debt          10000 non-null  float64
 20  Total_EMI_per_month       10000 non-null  float64
dtypes: float64(17), int64(1), object(3)
memory usage: 1.6+ MB

In [32]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  object
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Mix                10000 non-null  object
 9   Payment_Behaviour         10000 non-null  object
 10  Age                       10000 non-null  float64
 11  Annual_Income             10000 non-null  float64
 12  Num_Bank_Accounts         10000 non-null  float64
 13  Num_Credit_Card           10000 non-null  float64
 14  Interest_Rate             10000 non-null  float64
 15  Num_of_Loan               10000 non-null  float64
 16  Monthly_Inhand_Salary     10000 non-null  float64
 17  Changed_Credit_Limit      10000 non-null  float64
 18  Outstanding_Debt          10000 non-null  float64
 19  Total_EMI_per_month       10000 non-null  float64
dtypes: float64(17), object(3)
memory usage: 1.5+ MB

In [33]:
train.describe()

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Amount_invested_monthly,Monthly_Balance,Credit_Score,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
count,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,21.263100,13.381300,5.79400,32.306216,220.501400,195.497580,400.130732,1.880700,33.33680,50318.451889,5.382900,5.538000,14.468200,3.525700,4182.906254,10.435633,1428.996096,105.114322
std,14.778976,6.217876,3.86772,5.093599,99.204263,196.150962,211.034108,0.679789,10.73122,38171.440801,2.566271,2.096186,8.687977,2.441585,3175.891720,6.501954,1158.852422,125.502925
min,0.000000,0.000000,0.00000,20.719745,2.000000,0.000000,0.007760,1.000000,14.00000,7006.035000,0.000000,0.000000,1.000000,0.000000,303.645417,0.500000,0.230000,0.000000
25%,10.000000,9.000000,3.00000,28.075839,144.000000,74.056997,268.741936,1.000000,24.00000,19259.307500,4.000000,4.000000,7.000000,2.000000,1626.342083,5.507500,562.340000,28.588769
50%,18.000000,14.000000,6.00000,32.310153,219.000000,130.089440,334.854343,2.000000,33.00000,36875.140000,5.000000,5.000000,13.000000,3.000000,3073.272917,9.410000,1168.235000,65.971478
75%,28.000000,18.000000,8.00000,36.491502,301.000000,234.960725,470.351899,2.000000,42.00000,71507.587500,7.000000,7.000000,20.000000,5.000000,5936.870000,14.630000,1960.420000,144.429302
max,67.000000,28.000000,17.00000,47.103409,404.000000,1674.337665,1567.208309,3.000000,56.00000,179987.280000,10.000000,11.000000,34.000000,9.000000,15167.180000,29.980000,4998.070000,1701.955013

In [34]:
train.describe(include='O')

       Payment_of_Min_Amount Credit_Mix               Payment_Behaviour
count                  10000      10000                           10000
unique                     3          3                               6
top                      Yes   Standard  Low_spent_Small_value_payments
freq                    5269       4591                            3416

In [35]:
test.describe()

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Amount_invested_monthly,Monthly_Balance,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,21.097900,13.255200,5.752500,32.186729,221.825800,193.117531,400.580605,33.482000,50108.745203,5.340400,5.528100,14.472300,3.544600,4166.494700,10.416235,1416.394165,103.957612
std,14.797811,6.251238,3.865998,5.159005,99.213024,195.419810,212.389930,10.739097,38406.986599,2.586039,2.090609,8.773878,2.426891,3194.843717,6.521728,1148.313667,121.991063
min,0.000000,0.000000,0.000000,20.172942,2.000000,0.000000,1.222495,14.000000,7006.035000,0.000000,0.000000,1.000000,0.000000,303.645417,0.500000,0.340000,0.000000
25%,10.000000,9.000000,3.000000,27.894659,145.000000,72.723155,270.578579,25.000000,19214.681250,3.000000,4.000000,7.000000,2.000000,1616.490417,5.407500,560.410000,29.240525
50%,18.000000,14.000000,5.000000,32.166358,220.000000,128.333887,336.320248,33.000000,36475.525000,5.000000,5.000000,13.000000,3.000000,3052.810833,9.340000,1159.810000,65.377135
75%,28.000000,18.000000,8.000000,36.504712,304.000000,234.830616,465.525296,42.000000,71025.400000,7.000000,7.000000,20.000000,5.000000,5913.288333,14.832500,1941.615000,142.311157
max,67.000000,28.000000,29.000000,50.000000,404.000000,1804.355694,1533.102266,56.000000,179987.280000,10.000000,11.000000,34.000000,9.000000,15204.633333,29.970000,4997.050000,1701.955013

In [36]:
test.describe(include='O')

       Payment_of_Min_Amount Credit_Mix               Payment_Behaviour
count                  10000      10000                           10000
unique                     3          3                               6
top                      Yes   Standard  Low_spent_Small_value_payments
freq                    5167       4590                            3498

In [37]:
train.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Score                0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [38]:
test.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

## 데이터 전처리

In [39]:
#타겟 컬럼(분석대상)
set(train.columns) - set(test.columns)

{'Credit_Score'}

In [40]:
target = train.pop('Credit_Score')

In [41]:
obj_cols = train.select_dtypes(include='object').columns

In [42]:
#lightGBM 사용 시 범주형을 category로 바꾸는 것으로도 인코딩 없이 분석가능 
for col in obj_cols:
    train[col] = train[col].astype('category')
    test[col] = test[col].astype('category')

### 검증 데이터 나누기

In [44]:
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_val,y_train,y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0
)

print('x_train :', x_train.shape)
print('x_val :', x_val.shape)
print('y_train :', y_train.shape)
print('y_val :', y_val.shape)

x_train : (8000, 20)
x_val : (2000, 20)
y_train : (8000,)
y_val : (2000,)

### 분석(랜덤포레스트)

In [46]:
import lightgbm as lgb

In [50]:
model = lgb.LGBMClassifier(random_state=0, verbose=-1)
model.fit(x_train,y_train)
pred = model.predict(x_val)
pred

array([2, 2, 2, ..., 3, 2, 2])

### 평가

In [52]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [55]:
accuracy = accuracy_score(pred, y_val)
print('정확도 :', accuracy)

정확도 : 0.6985

In [57]:
f1 = f1_score(pred, y_val, average='micro')
print('f1 스코어 :', f1)

f1 스코어 : 0.6985

### 결과제출

In [58]:
result = model.predict(test)
result

array([2, 1, 1, ..., 1, 1, 2])

In [60]:
submit = pd.DataFrame({'pred' : result})
submit.to_csv('result.csv', index=False)

In [61]:
submit

      pred
0        2
1        1
2        1
3        2
4        1
...    ...
9995     2
9996     2
9997     1
9998     1
9999     2

[10000 rows x 1 columns]