## 이진분류(당뇨병 여부 예측)

In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('diabetes_train.csv')
test = pd.read_csv('diabetes_test.csv')

### 탐색적 데이터 분석

In [3]:
print("train :", train.shape)
print("test :", test.shape)

train : (614, 9)
test : (154, 8)

In [4]:
train.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,118,58,36,94,33.3,0.261,23,0
1,3,173,78,39,185,33.8,0.970,31,1

In [5]:
test.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,3,102,74,0,0,29.5,0.121,32
1,5,104,74,0,0,28.8,0.153,48

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               614 non-null    int64
 1   Glucose                   614 non-null    int64
 2   BloodPressure             614 non-null    int64
 3   SkinThickness             614 non-null    int64
 4   Insulin                   614 non-null    int64
 5   BMI                       614 non-null    float64
 6   DiabetesPedigreeFunction  614 non-null    float64
 7   Age                       614 non-null    int64
 8   Outcome                   614 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 43.3 KB

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               154 non-null    int64
 1   Glucose                   154 non-null    int64
 2   BloodPressure             154 non-null    int64
 3   SkinThickness             154 non-null    int64
 4   Insulin                   154 non-null    int64
 5   BMI                       154 non-null    float64
 6   DiabetesPedigreeFunction  154 non-null    float64
 7   Age                       154 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 9.8 KB

In [8]:
train.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,3.789902,120.659609,69.366450,20.969055,80.382736,32.067427,0.475490,33.250814,0.343648
std,3.384519,32.556686,18.847224,15.923677,111.332249,7.888971,0.326519,11.789160,0.475313
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.500000,0.000000,0.000000,27.300000,0.245500,24.000000,0.000000
50%,3.000000,116.000000,72.000000,23.000000,36.000000,32.100000,0.381500,29.000000,0.000000
75%,6.000000,140.750000,80.000000,32.000000,128.750000,36.600000,0.629750,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,680.000000,67.100000,2.420000,81.000000,1.000000

In [10]:
test.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000
mean,4.064935,121.831169,68.064935,18.811688,77.474026,31.694156,0.457468,33.201299
std,3.311054,29.611163,21.297358,16.001131,130.046960,7.883533,0.350588,11.682275
min,0.000000,56.000000,0.000000,0.000000,0.000000,0.000000,0.085000,21.000000
25%,1.000000,99.000000,62.500000,0.000000,0.000000,27.500000,0.234250,24.000000
50%,3.000000,119.500000,70.000000,20.500000,0.000000,32.000000,0.334500,29.000000
75%,6.000000,139.750000,80.000000,32.000000,105.750000,36.100000,0.592750,40.000000
max,13.000000,197.000000,114.000000,50.000000,846.000000,52.300000,2.329000,69.000000

In [11]:
train.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
test.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

### 데이터 전처리(데이터 나누기)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
#대상 컬럼
set(train) - set(test)

{'Outcome'}

In [16]:
target = train.pop('Outcome')

In [19]:
x_train,x_val,y_train,y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0,
)

In [20]:
print('x_train :', x_train.shape)
print('x_val :', x_val.shape)
print('y_train :', y_train.shape)
print('y_val :', y_val.shape)

x_train : (491, 8)
x_val : (123, 8)
y_train : (491,)
y_val : (123,)

### 학습(랜덤포레스트)

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
rf = RandomForestClassifier(random_state=0)
rf.fit(x_train, y_train)

pred = rf.predict_proba(x_val)
pred

array([[0.88, 0.12],
       [0.29, 0.71],
       [0.41, 0.59],
       [0.75, 0.25],
       [0.89, 0.11],
       [0.76, 0.24],
       [0.49, 0.51],
       [0.6 , 0.4 ],
       [0.48, 0.52],
       [0.85, 0.15],
       [0.99, 0.01],
       [0.29, 0.71],
       [0.73, 0.27],
       [0.87, 0.13],
       [0.87, 0.13],
       [0.72, 0.28],
       [1.  , 0.  ],
       [0.29, 0.71],
       [0.45, 0.55],
       [0.38, 0.62],
       [0.3 , 0.7 ],
       [0.94, 0.06],
       [0.94, 0.06],
       [0.98, 0.02],
       [0.84, 0.16],
       [0.7 , 0.3 ],
       [0.42, 0.58],
       [0.91, 0.09],
       [1.  , 0.  ],
       [0.87, 0.13],
       [0.69, 0.31],
       [0.23, 0.77],
       [0.32, 0.68],
       [0.52, 0.48],
       [0.63, 0.37],
       [0.96, 0.04],
       [0.43, 0.57],
       [0.62, 0.38],
       [0.61, 0.39],
       [0.81, 0.19],
       [0.87, 0.13],
       [0.42, 0.58],
       [0.93, 0.07],
       [0.87, 0.13],
       [0.31, 0.69],
       [0.89, 0.11],
       [0.97, 0.03],
       [0.99, 0.01],
       [0.12, 0.88],
       [0.3 , 0.7 ],
       [0.29, 0.71],
       [0.28, 0.72],
       [0.49, 0.51],
       [0.34, 0.66],
       [0.38, 0.62],
       [0.83, 0.17],
       [0.81, 0.19],
       [0.42, 0.58],
       [0.73, 0.27],
       [0.31, 0.69],
       [0.35, 0.65],
       [0.44, 0.56],
       [0.79, 0.21],
       [0.93, 0.07],
       [0.44, 0.56],
       [0.66, 0.34],
       [0.67, 0.33],
       [0.18, 0.82],
       [0.55, 0.45],
       [0.79, 0.21],
       [0.59, 0.41],
       [0.85, 0.15],
       [0.4 , 0.6 ],
       [0.98, 0.02],
       [0.9 , 0.1 ],
       [0.99, 0.01],
       [0.88, 0.12],
       [0.96, 0.04],
       [0.53, 0.47],
       [0.39, 0.61],
       [0.28, 0.72],
       [0.14, 0.86],
       [0.56, 0.44],
       [0.91, 0.09],
       [0.7 , 0.3 ],
       [0.61, 0.39],
       [0.4 , 0.6 ],
       [0.67, 0.33],
       [0.85, 0.15],
       [0.4 , 0.6 ],
       [0.95, 0.05],
       [0.17, 0.83],
       [0.97, 0.03],
       [0.67, 0.33],
       [0.43, 0.57],
       [0.68, 0.32],
       [0.66, 0.34],
       [0.78, 0.22],
       [0.15, 0.85],
       [0.96, 0.04],
       [0.44, 0.56],
       [0.99, 0.01],
       [0.47, 0.53],
       [0.91, 0.09],
       [0.54, 0.46],
       [0.39, 0.61],
       [0.83, 0.17],
       [0.74, 0.26],
       [0.53, 0.47],
       [0.78, 0.22],
       [0.57, 0.43],
       [0.57, 0.43],
       [0.68, 0.32],
       [0.61, 0.39],
       [0.79, 0.21],
       [0.8 , 0.2 ],
       [1.  , 0.  ],
       [0.24, 0.76],
       [0.96, 0.04],
       [0.4 , 0.6 ],
       [0.51, 0.49],
       [0.7 , 0.3 ],
       [0.74, 0.26]])

### 평가(roc_auc)

In [24]:
from sklearn.metrics import roc_auc_score

In [31]:
roc_auc = roc_auc_score(y_val, pred[:,-1])
print('roc_auc :', roc_auc)

roc_auc : 0.8002739726027398

### 예측결과 제출

In [33]:
pred = rf.predict_proba(test)
pred

array([[0.83, 0.17],
       [0.67, 0.33],
       [0.89, 0.11],
       [0.96, 0.04],
       [0.91, 0.09],
       [0.26, 0.74],
       [0.6 , 0.4 ],
       [0.45, 0.55],
       [0.47, 0.53],
       [0.81, 0.19],
       [0.56, 0.44],
       [0.56, 0.44],
       [0.81, 0.19],
       [0.39, 0.61],
       [0.5 , 0.5 ],
       [0.59, 0.41],
       [0.53, 0.47],
       [0.83, 0.17],
       [0.35, 0.65],
       [0.73, 0.27],
       [0.87, 0.13],
       [0.29, 0.71],
       [0.99, 0.01],
       [0.27, 0.73],
       [0.82, 0.18],
       [0.58, 0.42],
       [0.55, 0.45],
       [0.6 , 0.4 ],
       [0.17, 0.83],
       [0.45, 0.55],
       [0.84, 0.16],
       [0.41, 0.59],
       [0.56, 0.44],
       [0.8 , 0.2 ],
       [0.39, 0.61],
       [0.74, 0.26],
       [0.95, 0.05],
       [0.79, 0.21],
       [0.97, 0.03],
       [0.9 , 0.1 ],
       [0.46, 0.54],
       [0.07, 0.93],
       [0.32, 0.68],
       [0.88, 0.12],
       [0.31, 0.69],
       [0.92, 0.08],
       [0.95, 0.05],
       [0.4 , 0.6 ],
       [0.92, 0.08],
       [0.33, 0.67],
       [0.99, 0.01],
       [0.24, 0.76],
       [0.54, 0.46],
       [0.45, 0.55],
       [0.3 , 0.7 ],
       [0.79, 0.21],
       [0.24, 0.76],
       [0.99, 0.01],
       [0.17, 0.83],
       [0.27, 0.73],
       [0.65, 0.35],
       [0.71, 0.29],
       [0.96, 0.04],
       [0.55, 0.45],
       [0.99, 0.01],
       [0.38, 0.62],
       [0.76, 0.24],
       [0.21, 0.79],
       [0.98, 0.02],
       [0.41, 0.59],
       [0.94, 0.06],
       [0.68, 0.32],
       [0.58, 0.42],
       [0.63, 0.37],
       [0.83, 0.17],
       [0.98, 0.02],
       [0.85, 0.15],
       [0.7 , 0.3 ],
       [0.34, 0.66],
       [0.25, 0.75],
       [0.9 , 0.1 ],
       [0.94, 0.06],
       [0.58, 0.42],
       [0.95, 0.05],
       [0.96, 0.04],
       [0.78, 0.22],
       [0.32, 0.68],
       [0.86, 0.14],
       [0.85, 0.15],
       [0.89, 0.11],
       [0.77, 0.23],
       [0.89, 0.11],
       [1.  , 0.  ],
       [0.36, 0.64],
       [0.91, 0.09],
       [0.95, 0.05],
       [0.98, 0.02],
       [0.08, 0.92],
       [0.98, 0.02],
       [0.85, 0.15],
       [0.71, 0.29],
       [0.26, 0.74],
       [0.48, 0.52],
       [0.76, 0.24],
       [0.2 , 0.8 ],
       [0.59, 0.41],
       [0.86, 0.14],
       [0.67, 0.33],
       [0.27, 0.73],
       [0.78, 0.22],
       [0.43, 0.57],
       [0.66, 0.34],
       [0.97, 0.03],
       [0.91, 0.09],
       [0.5 , 0.5 ],
       [0.42, 0.58],
       [0.29, 0.71],
       [0.32, 0.68],
       [0.98, 0.02],
       [0.93, 0.07],
       [0.49, 0.51],
       [0.97, 0.03],
       [0.74, 0.26],
       [0.82, 0.18],
       [0.59, 0.41],
       [0.53, 0.47],
       [0.97, 0.03],
       [0.83, 0.17],
       [0.64, 0.36],
       [0.98, 0.02],
       [0.8 , 0.2 ],
       [0.65, 0.35],
       [0.97, 0.03],
       [0.99, 0.01],
       [0.99, 0.01],
       [0.77, 0.23],
       [0.86, 0.14],
       [0.32, 0.68],
       [0.67, 0.33],
       [0.97, 0.03],
       [0.55, 0.45],
       [0.23, 0.77],
       [0.27, 0.73],
       [0.57, 0.43],
       [0.84, 0.16],
       [0.74, 0.26],
       [0.93, 0.07],
       [0.1 , 0.9 ],
       [0.94, 0.06],
       [0.47, 0.53],
       [0.77, 0.23],
       [0.94, 0.06],
       [0.31, 0.69],
       [0.59, 0.41]])

In [34]:
submit = pd.DataFrame({'pred' : pred[:,-1]})
submit.to_csv('result.csv', index=False)
submit.head()

   pred
0  0.17
1  0.33
2  0.11
3  0.04
4  0.09

### 성능개선

In [37]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler

### 적합 스케일링 탐색

In [38]:
scaler_dic = {
    "MinMaxScaler" : MinMaxScaler(),
    "StandardScaler" : StandardScaler(),
    "RobustScaler" : RobustScaler(),
    "MaxAbsScaler" : MaxAbsScaler(),
}

In [41]:
for name,scaler in scaler_dic.items():

    train = pd.read_csv('diabetes_train.csv')
    test = pd.read_csv('diabetes_test.csv')

    target = train.pop('Outcome')

    #스케일링 모델별로 실행
    train = scaler.fit_transform(train)
    test = scaler.transform(test)

    x_train,x_val,y_train,y_val = train_test_split(
        train,
        target,
        test_size=0.2,
        random_state=0
    )
        
    model = RandomForestClassifier(random_state=0)
    model.fit(x_train,y_train)

    pred = model.predict_proba(x_val)

    roc_auc = roc_auc_score(y_val, pred[:,-1])
    
    print(name,":",roc_auc)

MinMaxScaler : 0.8031506849315069
StandardScaler : 0.8005479452054794
RobustScaler : 0.7987671232876713
MaxAbsScaler : 0.8002739726027398

### 하이퍼파라미터 탐색

### max_depth 탐색

In [44]:
train = pd.read_csv('diabetes_train.csv')
test = pd.read_csv('diabetes_test.csv')

target = train.pop('Outcome')

# min-max 스케일링
scaler = MinMaxScaler()
train = scaler.fit_transform(train)
test = scaler.transform(test)

x_train,x_val,y_train,y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0
)

for depth in range(3,10) :
    model = RandomForestClassifier(max_depth=depth, random_state=0)
    model.fit(x_train,y_train) 

    pred = model.predict_proba(x_val)
    roc_auc = roc_auc_score(y_val, pred[:, -1])
    print(f'depth({depth}) : {roc_auc}')

depth(3) : 0.8120547945205479
depth(4) : 0.812054794520548
depth(5) : 0.8153424657534246
depth(6) : 0.812876712328767
depth(7) : 0.8076712328767124
depth(8) : 0.8093150684931507
depth(9) : 0.8046575342465753

### n_estimators 탐색

In [46]:
train = pd.read_csv('diabetes_train.csv')
test = pd.read_csv('diabetes_test.csv')

target = train.pop('Outcome')

# min-max 스케일링
scaler = MinMaxScaler()
train = scaler.fit_transform(train)
test = scaler.transform(test)

x_train,x_val,y_train,y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0
)

for n in range(100,1000,100) :
    model = RandomForestClassifier(max_depth=5, n_estimators=n, random_state=0)
    model.fit(x_train,y_train) 

    pred = model.predict_proba(x_val)
    roc_auc = roc_auc_score(y_val, pred[:, -1])
    print(f'n_estimators({n}) : {roc_auc}')

n_estimators(100) : 0.8153424657534246
n_estimators(200) : 0.8219178082191781
n_estimators(300) : 0.8202739726027397
n_estimators(400) : 0.8227397260273972
n_estimators(500) : 0.8246575342465753
n_estimators(600) : 0.8243835616438356
n_estimators(700) : 0.8241095890410959
n_estimators(800) : 0.8224657534246576
n_estimators(900) : 0.8232876712328767

#### 최적의 파라미터
#### max_depth : 5
#### n_estimators : 500