In [68]:
import numpy as np
import pandas as pd

## S31.문자열, 형변환

In [2]:
df = pd.read_csv('delivery_time.csv')
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.'user'컬럼에서 user뒤에 있는 숫자 값만 추출하시오.

In [4]:
df['user_num'] = df['user'].replace(r'\D','',regex=True)
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,user_num
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275,275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36,36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176,176

#### 2.추출된 숫자 값을 모두 합한 값을 정수로 구하시오.

In [5]:
df['user_num'] = df['user_num'].astype('int')

result = int(df['user_num'].sum())
print("합 결과 :", result)

합 결과 : 261387

## S32.합계(열 방향), 상위 값 선택

In [6]:
df = pd.read_csv('school_data.csv')
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사
0  강아지  66  61  26  김선생  장선생  최선생
1  고양이  92  48  80  김선생  장선생  이선생
2   토끼  98   7   6  김선생  장선생  최선생
3   사자  17  99  14  김선생  유선생  최선생
4  호랑이  83  92  75  박선생  장선생  이선생

#### 1.수학,영어,국어 점수의 합을 구하시오.

In [7]:
df['total_score'] = df.sum(numeric_only=True, axis=1)
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사  total_score
0  강아지  66  61  26  김선생  장선생  최선생          153
1  고양이  92  48  80  김선생  장선생  이선생          220
2   토끼  98   7   6  김선생  장선생  최선생          111
3   사자  17  99  14  김선생  유선생  최선생          130
4  호랑이  83  92  75  박선생  장선생  이선생          250

#### 2.합이 가장 큰 상위 10명을 찾으시오.

In [9]:
df = df.sort_values('total_score', ascending=False)
df = df.iloc[0:10]

#### 3.찾은 10명의 수학 평균 점수를 구하시오.(반올림 후 정수 출력)

In [11]:
result = df['수학'].mean()
result = round(result)

print('수학 평균 :', result)

수학 평균 : 82

## S33. 데이터프레임 재구조화

In [16]:
df = pd.read_csv('school_data.csv')
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사
0  강아지  66  61  26  김선생  장선생  최선생
1  고양이  92  48  80  김선생  장선생  이선생
2   토끼  98   7   6  김선생  장선생  최선생
3   사자  17  99  14  김선생  유선생  최선생
4  호랑이  83  92  75  박선생  장선생  이선생

#### 1.과목에 상관없이 점수가 가장 작은 점수 25개를 찾으시오.

In [17]:
df = df.melt(id_vars=['이름'], value_vars=['수학','영어','국어'], var_name='과목', value_name='점수')
df = df.nsmallest(25, '점수')

print("데이터 수 :", len(df))
df.head()

데이터 수 : 25

     이름  과목  점수
67   기린  국어   1
79  침팬지  국어   1
24   참새  수학   2
44  코알라  영어   3
87  펠리칸  국어   3

#### 2.찾은 점수 25개의 합을 정수로 구하시오.

In [18]:
result = int(df['점수'].sum())
print("점수의 합 :", result)

점수의 합 : 420

## S34.데이터 합치기(concat)

In [19]:
df = pd.read_csv('school_data.csv')
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사
0  강아지  66  61  26  김선생  장선생  최선생
1  고양이  92  48  80  김선생  장선생  이선생
2   토끼  98   7   6  김선생  장선생  최선생
3   사자  17  99  14  김선생  유선생  최선생
4  호랑이  83  92  75  박선생  장선생  이선생

In [20]:
science_df = pd.read_csv('school_data_science.csv')
science_df.head()

    이름  과학 과학교사
0  강아지  66  황선생
1  고양이  92  임선생
2   토끼  98  황선생
3   사자  17  임선생
4  호랑이  83  임선생

#### 1.주어진 두 csv파일을 학생 순서를 기준으로 병합하시오.(단 파일의 학생 순서는 동일하다.)

In [21]:
df = pd.concat([df, science_df], axis=1)
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사   이름  과학 과학교사
0  강아지  66  61  26  김선생  장선생  최선생  강아지  66  황선생
1  고양이  92  48  80  김선생  장선생  이선생  고양이  92  임선생
2   토끼  98   7   6  김선생  장선생  최선생   토끼  98  황선생
3   사자  17  99  14  김선생  유선생  최선생   사자  17  임선생
4  호랑이  83  92  75  박선생  장선생  이선생  호랑이  83  임선생

#### 2.학생별로 수학,영어,국어,과학 점수의 평균을 구하시오.

In [22]:
df['total_score'] = df.mean(numeric_only=True, axis=1)
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사   이름  과학 과학교사  total_score
0  강아지  66  61  26  김선생  장선생  최선생  강아지  66  황선생        54.75
1  고양이  92  48  80  김선생  장선생  이선생  고양이  92  임선생        78.00
2   토끼  98   7   6  김선생  장선생  최선생   토끼  98  황선생        52.25
3   사자  17  99  14  김선생  유선생  최선생   사자  17  임선생        36.75
4  호랑이  83  92  75  박선생  장선생  이선생  호랑이  83  임선생        83.25

#### 3.평균점수가 60점 이상인 인원 수를 계산하시오.

In [23]:
cond = df['total_score'] >= 60
print("대상자 수 :", sum(cond))

대상자 수 : 9

## S35.데이터 합치기(merge)

In [27]:
df = pd.read_csv('school_data.csv')
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사
0  강아지  66  61  26  김선생  장선생  최선생
1  고양이  92  48  80  김선생  장선생  이선생
2   토끼  98   7   6  김선생  장선생  최선생
3   사자  17  99  14  김선생  유선생  최선생
4  호랑이  83  92  75  박선생  장선생  이선생

In [28]:
social_df = pd.read_csv('school_data_social.csv')
social_df.head()

    이름  사회 사회교사
0   기린  47  오선생
1    매  61  우선생
2    곰  48  우선생
3  개구리   7  오선생
4  코끼리  99  오선생

#### 1.두 csv파일을 '이름'을 기준으로 합치시오.

In [29]:
df = pd.merge(df, social_df, on='이름')
df.head()

    이름  수학  영어  국어 수학교사 영어교사 국어교사  사회 사회교사
0  강아지  66  61  26  김선생  장선생  최선생  58  오선생
1  고양이  92  48  80  김선생  장선생  이선생  10  오선생
2   토끼  98   7   6  김선생  장선생  최선생  30  오선생
3   사자  17  99  14  김선생  유선생  최선생  97  우선생
4  호랑이  83  92  75  박선생  장선생  이선생  34  오선생

#### 2.영어교사가 장선생이면서 사회교사가 오선생인 학생들을 필터링하시오.

In [30]:
cond1 = df['영어교사'] == '장선생'
cond2 = df['사회교사'] == '오선생'
df = df[cond1 & cond2]

#### 3.필터링된 학생들의 수학 점수를 모두 더한 후 정수를 구하시오.

In [31]:
result = int(df['수학'].sum())
print("수학점수 합계 :", result)

수학점수 합계 : 602

## S36.조건별 변환

In [32]:
df = pd.read_csv('sales.csv')
df.head()

   지역코드  거래ID    판매금액
0   101  T001  1000.0
1   101  T002  1200.0
2   101  T003     NaN
3   101  T004  1500.0
4   101  T005  1100.0

#### 1.결측된 판매금액은 해당 지역의 평균 판매금액으로 결측값을 대체하시오.

In [37]:
mean_value = df.groupby('지역코드')['판매금액'].transform('mean')
df['판매금액'] = df['판매금액'].fillna(mean_value)
df.head()

   지역코드  거래ID    판매금액
0   101  T001  1000.0
1   101  T002  1200.0
2   101  T003  1200.0
3   101  T004  1500.0
4   101  T005  1100.0

#### 2.각 거래마다 '판매금액'과 해당 지역의 평균 판매금액의 '차이'를 절대값으로 구하시오.

In [38]:
df['지역평균'] = df.groupby('지역코드')['판매금액'].transform('mean')
df['평균차이'] = abs(df['판매금액'] - df['지역평균'])
df.head()

   지역코드  거래ID    판매금액    지역평균   평균차이
0   101  T001  1000.0  1200.0  200.0
1   101  T002  1200.0  1200.0    0.0
2   101  T003  1200.0  1200.0    0.0
3   101  T004  1500.0  1200.0  300.0
4   101  T005  1100.0  1200.0  100.0

#### 3.각 지역에서 차이값의 평균을 구한 후, 이 값이 가장 큰 지역의 지역코드를 구하시오.

In [40]:
result = df.groupby('지역코드')['평균차이'].mean()
print("차이가 가장 큰 지역 :", result.idxmax())
print("차이가 가장 큰 값 :", result.max())

차이가 가장 큰 지역 : 103
차이가 가장 큰 값 : 260.0

## S37.재구조화(unstack), 맵핑

In [60]:
df = pd.read_csv('store_sales.csv')
df.head()

  매장코드 요일  판매수량    단가
0    A  월    10  2000
1    A  화    15  1500
2    A  토    28  3332
3    B  월     5  2500
4    B  금     8  2200

#### 1.각 행에서 판매수량과 단가를 이용하여 매출액을 계산하시오.

In [61]:
df['매출액'] = df['판매수량'] * df['단가']
df.head()

  매장코드 요일  판매수량    단가    매출액
0    A  월    10  2000  20000
1    A  화    15  1500  22500
2    A  토    28  3332  93296
3    B  월     5  2500  12500
4    B  금     8  2200  17600

#### 2.요일을 평일과 주말로 구분하고, 매장별 평일과 주말 매출액 합계를 구하시오.

In [62]:
mapping = {
    '월':'평일',
    '화':'평일',
    '수':'평일',
    '목':'평일',
    '금':'평일',
    '토':'주말',
    '일':'주말',
    }
df['구분'] = df['요일'].map(mapping)
df.head()

  매장코드 요일  판매수량    단가    매출액  구분
0    A  월    10  2000  20000  평일
1    A  화    15  1500  22500  평일
2    A  토    28  3332  93296  주말
3    B  월     5  2500  12500  평일
4    B  금     8  2200  17600  평일

In [63]:
sales_df = df.groupby(['매장코드','구분'])['매출액'].sum()
sales_df

매장코드  구분
A     주말     93296
      평일     42500
B     주말     50983
      평일     30100
C     주말    317975
      평일     76000
D     주말    202481
      평일     37800
E     주말    197236
      평일     43600
Name: 매출액, dtype: int64

In [64]:
sales_df = sales_df.unstack(level=-1)

In [65]:
sales_df.head()

구분        주말     평일
매장코드
A      93296  42500
B      50983  30100
C     317975  76000
D     202481  37800
E     197236  43600

#### 3.매장별 평일과 주말 매출액 차이를 절대값으로 구하시오.
####   이후, 모든 매장 중 가장 큰 절대값 차이를 찾으시오.

In [66]:
sales_df['매출차이'] = abs(sales_df['평일']-sales_df['주말'])
sales_df.head()

구분        주말     평일    매출차이
매장코드
A      93296  42500   50796
B      50983  30100   20883
C     317975  76000  241975
D     202481  37800  164681
E     197236  43600  153636

In [67]:
result = sales_df['매출차이'].max()
print("가장 큰 절대값 :", result)

가장 큰 절대값 : 241975

## S38.피벗테이블

In [69]:
df = pd.read_csv('region_sales.csv')
df.head()

         Date Region Product  Channel  Sales
0  2025-01-05  North       A   Online    120
1  2025-01-07  South       A  Offline    150
2  2025-02-10  North       B   Online    200
3  2023-02-12  North       A   Online    130
4  2025-03-15   East       A  Offline    100

#### 1.각 Region과 Channel 조합별로 제품(Product) A,B의 총 판매액을 계산하시오.

In [82]:
test = df.groupby(['Region', 'Channel', 'Product'])['Sales'].sum()
test.unstack()

Product           A    B
Region Channel
East   Offline  100  105
       Online   205  210
North  Offline  140  180
       Online   440  420
South  Offline  150  145
       Online   160  170
West   Offline  110  115
       Online   135  130

In [74]:
pivot_table = pd.pivot_table(df, 
                             index=['Region', 'Channel'],
                             columns='Product',
                             values='Sales',
                             aggfunc='sum',
                            )
pivot_table

Product           A    B
Region Channel
East   Offline  100  105
       Online   205  210
North  Offline  140  180
       Online   440  420
South  Offline  150  145
       Online   160  170
West   Offline  110  115
       Online   135  130

#### 제품 A의 매출 비율(A비율)을 구하시오.
#### A비율 = (제품A의 판매액) / (제품A 판매액 + 제품B 판매액)

In [76]:
pivot_table['총판매액'] = pivot_table['A'] + pivot_table['B']
pivot_table['A비율'] = pivot_table['A']/pivot_table['총판매액']
pivot_table

Product           A    B  총판매액       A비율
Region Channel
East   Offline  100  105   205  0.487805
       Online   205  210   415  0.493976
North  Offline  140  180   320  0.437500
       Online   440  420   860  0.511628
South  Offline  150  145   295  0.508475
       Online   160  170   330  0.484848
West   Offline  110  115   225  0.488889
       Online   135  130   265  0.509434

#### 3.A비율 중 최댓값을 찾아 반올림하여 소수 둘째 자리까지 구하시오.

In [77]:
result = pivot_table['A비율'].max()
result = round(result,2)
print("A비율 최댓값 :", result)

A비율 최댓값 : 0.51

## S39.재구조화(melt), 그룹핑

In [85]:
df = pd.read_csv('monthly_sales.csv')
df.head()

  Region  Jan  Feb  Mar
0  Seoul  120  135  110
1  Seoul   95  108  145
2  Seoul  200  179  140
3  Seoul  150  155  170
4  Seoul  110   98  190

#### 1.지역(Region)과 월(Jan,Feb,Mar)별 매출(Sales) 합계를 구하시오.

In [86]:
df = pd.melt(
    df,
    id_vars='Region',
    value_vars=['Jan', 'Feb', 'Mar'],
    var_name='Month',
    value_name='Sales'         
)
df.head()

  Region Month  Sales
0  Seoul   Jan    120
1  Seoul   Jan     95
2  Seoul   Jan    200
3  Seoul   Jan    150
4  Seoul   Jan    110

#### 2.위에서 구한 결과 중, 매출 합계(Sales)가 1400을 초과하는 경우가 몇 건인지 구하시오.

In [89]:
group_df = df.groupby(['Region','Month'])['Sales'].sum()
group_df

[Region   Month
 Busan    Feb      1323
          Jan      1256
          Mar      1371
 Daegu    Feb      1365
          Jan      1317
          Mar      1538
 Daejeon  Feb      1348
          Jan      1350
          Mar      1400
 Incheon  Feb      1444
          Jan      1436
          Mar      1466
 Seoul    Feb      1425
          Jan      1385
          Mar      1420
 Name: Sales, dtype: int64]

In [ ]:
cond = group_df['']