In [1]:
import numpy as np
import pandas as pd

## S21.시간 간의 차이 계산(분), 필터링

In [7]:
df = pd.read_csv('delivery_time.csv')
print("구조 : ", df.shape)
df.head()

구조 :  (1000, 7)

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문시간    1000 non-null   object
 1   실제도착시간  1000 non-null   object
 2   예상도착시간  1000 non-null   object
 3   앱종류     1000 non-null   object
 4   거리      1000 non-null   float64
 5   결제종류    1000 non-null   object
 6   user    1000 non-null   object
dtypes: float64(1), object(6)
memory usage: 54.8+ KB

#### 1.예상도착시간보다 늦게 도착한 건수를 찾으시오.

In [10]:
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문시간    1000 non-null   datetime64[ns]
 1   실제도착시간  1000 non-null   datetime64[ns]
 2   예상도착시간  1000 non-null   datetime64[ns]
 3   앱종류     1000 non-null   object
 4   거리      1000 non-null   float64
 5   결제종류    1000 non-null   object
 6   user    1000 non-null   object
dtypes: datetime64[ns](3), float64(1), object(3)
memory usage: 54.8+ KB

In [12]:
cond = df['예상도착시간'] < df['실제도착시간']
df = df[cond]

print('건수 :', len(df))

건수 : 510

#### 2.이 중 거리가 7km 이상인 데이터의 수를 정수로 구하시오.

In [14]:
cond = df['거리'] >= 7
print('건수 :', sum(cond))

건수 : 311

## S22.시간 간의 차이 계산(분), 그룹핑

In [19]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.주문 시간과 실제 도착 시간의 차이를 분 단위로 계산하시오.

In [20]:
df["배달시간"] = df['실제도착시간'] - df['주문시간']
df["배달시간"] = df['배달시간'].dt.total_seconds()/60
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,배달시간
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275,68.283333
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,22.166667
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36,71.816667
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,29.950000
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176,89.500000

#### 2.앱 종류별로 평균 도착 시간(분)을 계산하시오.

In [21]:
mean_df = df.groupby('앱종류').mean(numeric_only=True)
mean_df.head()

            거리       배달시간
앱종류
배고팡  10.109911  61.818694
배달왕   9.655749  63.517864
여기여   9.854316  62.343110

#### 평균적으로 가장 빠른 앱 종류를 찾고, 해당 앱의 평균 도착 시간을 분으로 반올림하여 정수로 구하시오.

In [22]:
mean_df = mean_df.sort_values('배달시간', ascending=True)
mean_df = mean_df.reset_index(drop=False)

mean_df

   앱종류         거리       배달시간
0  배고팡  10.109911  61.818694
1  여기여   9.854316  62.343110
2  배달왕   9.655749  63.517864

In [26]:
print('가장 빠른 앱 :', mean_df.iloc[0,0])
print('평균도착시간(분) :', round(mean_df.iloc[0,-1]))

가장 빠른 앱 : 배고팡
평균도착시간(분) : 62

## S23.시간 간의 차이 계산(분), 비율

In [31]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 각 결제 종류별로 실제 도착 시간이 예상 도착 시간보다 늦은 주문의 비율을 계산하시오.

In [32]:
df['지연시간'] = (df['실제도착시간'] - df['예상도착시간']).dt.total_seconds()/60
df['지연여부'] = df['지연시간'] > 0

result = df.groupby(['결제종류'])["지연여부"].mean()

result

결제종류
앱결제    0.556634
카드     0.489971
현금     0.488304
Name: 지연여부, dtype: float64

#### 비율 중 가장 큰 값을 반올림하여 소수 둘째 자리까지 구하시오.

In [34]:
print("비율이 가장 큰 결제종류 :", result.idxmax())
print("비율이 가장 큰 값:", round(result.max(),2))

비율이 가장 큰 결제종류 : 앱결제
비율이 가장 큰 값: 0.56

## S25.시간 간의 차이 계산(일)

In [35]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.각 사용자별로 첫 주문과 마지막 주문 사이의 시간 간격을 일 단위로 계산하시오.

In [46]:
user_min_order = df.groupby(['user'])['주문시간'].min()
user_max_order = df.groupby(['user'])['주문시간'].max()

user_min_order.name = 'min'
user_max_order.name = 'max'

order_df = pd.concat([user_min_order, user_max_order], axis=1)
order_df['시간간격'] = (order_df['max'] - order_df['min']).dt.days 
#order_df['test'] = (order_df['max'] - order_df['min']).dt.total_seconds()/60/60/24
order_df.head()

                         min                 max  시간간격
user
user_1   2023-01-08 12:52:59 2023-06-07 04:29:28   149
user_10  2022-10-22 20:13:05 2023-08-02 05:48:27   283
user_101 2023-06-26 01:43:40 2023-06-26 01:43:40     0
user_103 2022-12-04 09:06:03 2022-12-04 09:06:03     0
user_104 2023-06-13 18:24:38 2023-06-13 18:24:38     0

#### 2.시간차가 0일인 사용자를 제외하고, 나머지 사용자들의 평균 시간 각격(일 단위)을 계산하시오.

In [49]:
cond = order_df['시간간격'] > 0
order_df = order_df[cond]

mean_interval = order_df['시간간격'].mean()
print("mean_interval :", mean_interval)

mean_interval : 167.69463087248323

#### 3.평균 시간 간격보다 긴 시간 간격을 가진 사용자의 수를 정수로 구하시오.

In [50]:
cond = order_df['시간간격'] > mean_interval
print("사용자 수 :", sum(cond))

사용자 수 : 146