In [2]:
import numpy as np
import pandas as pd

## S21.시간 간의 차이 계산(분), 필터링

In [7]:
df = pd.read_csv('delivery_time.csv')
print("구조 : ", df.shape)
df.head()

구조 :  (1000, 7)

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문시간    1000 non-null   object
 1   실제도착시간  1000 non-null   object
 2   예상도착시간  1000 non-null   object
 3   앱종류     1000 non-null   object
 4   거리      1000 non-null   float64
 5   결제종류    1000 non-null   object
 6   user    1000 non-null   object
dtypes: float64(1), object(6)
memory usage: 54.8+ KB

#### 1.예상도착시간보다 늦게 도착한 건수를 찾으시오.

In [10]:
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문시간    1000 non-null   datetime64[ns]
 1   실제도착시간  1000 non-null   datetime64[ns]
 2   예상도착시간  1000 non-null   datetime64[ns]
 3   앱종류     1000 non-null   object
 4   거리      1000 non-null   float64
 5   결제종류    1000 non-null   object
 6   user    1000 non-null   object
dtypes: datetime64[ns](3), float64(1), object(3)
memory usage: 54.8+ KB

In [12]:
cond = df['예상도착시간'] < df['실제도착시간']
df = df[cond]

print('건수 :', len(df))

건수 : 510

#### 2.이 중 거리가 7km 이상인 데이터의 수를 정수로 구하시오.

In [14]:
cond = df['거리'] >= 7
print('건수 :', sum(cond))

건수 : 311

## S22.시간 간의 차이 계산(분), 그룹핑

In [19]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.주문 시간과 실제 도착 시간의 차이를 분 단위로 계산하시오.

In [20]:
df["배달시간"] = df['실제도착시간'] - df['주문시간']
df["배달시간"] = df['배달시간'].dt.total_seconds()/60
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,배달시간
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275,68.283333
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,22.166667
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36,71.816667
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,29.950000
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176,89.500000

#### 2.앱 종류별로 평균 도착 시간(분)을 계산하시오.

In [21]:
mean_df = df.groupby('앱종류').mean(numeric_only=True)
mean_df.head()

            거리       배달시간
앱종류
배고팡  10.109911  61.818694
배달왕   9.655749  63.517864
여기여   9.854316  62.343110

#### 평균적으로 가장 빠른 앱 종류를 찾고, 해당 앱의 평균 도착 시간을 분으로 반올림하여 정수로 구하시오.

In [22]:
mean_df = mean_df.sort_values('배달시간', ascending=True)
mean_df = mean_df.reset_index(drop=False)

mean_df

   앱종류         거리       배달시간
0  배고팡  10.109911  61.818694
1  여기여   9.854316  62.343110
2  배달왕   9.655749  63.517864

In [26]:
print('가장 빠른 앱 :', mean_df.iloc[0,0])
print('평균도착시간(분) :', round(mean_df.iloc[0,-1]))

가장 빠른 앱 : 배고팡
평균도착시간(분) : 62

## S23.시간 간의 차이 계산(분), 비율

In [31]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 각 결제 종류별로 실제 도착 시간이 예상 도착 시간보다 늦은 주문의 비율을 계산하시오.

In [32]:
df['지연시간'] = (df['실제도착시간'] - df['예상도착시간']).dt.total_seconds()/60
df['지연여부'] = df['지연시간'] > 0

result = df.groupby(['결제종류'])["지연여부"].mean()

result

결제종류
앱결제    0.556634
카드     0.489971
현금     0.488304
Name: 지연여부, dtype: float64

#### 비율 중 가장 큰 값을 반올림하여 소수 둘째 자리까지 구하시오.

In [34]:
print("비율이 가장 큰 결제종류 :", result.idxmax())
print("비율이 가장 큰 값:", round(result.max(),2))

비율이 가장 큰 결제종류 : 앱결제
비율이 가장 큰 값: 0.56

## S25.시간 간의 차이 계산(일)

In [35]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.각 사용자별로 첫 주문과 마지막 주문 사이의 시간 간격을 일 단위로 계산하시오.

In [46]:
user_min_order = df.groupby(['user'])['주문시간'].min()
user_max_order = df.groupby(['user'])['주문시간'].max()

user_min_order.name = 'min'
user_max_order.name = 'max'

order_df = pd.concat([user_min_order, user_max_order], axis=1)
order_df['시간간격'] = (order_df['max'] - order_df['min']).dt.days 
#order_df['test'] = (order_df['max'] - order_df['min']).dt.total_seconds()/60/60/24
order_df.head()

                         min                 max  시간간격
user
user_1   2023-01-08 12:52:59 2023-06-07 04:29:28   149
user_10  2022-10-22 20:13:05 2023-08-02 05:48:27   283
user_101 2023-06-26 01:43:40 2023-06-26 01:43:40     0
user_103 2022-12-04 09:06:03 2022-12-04 09:06:03     0
user_104 2023-06-13 18:24:38 2023-06-13 18:24:38     0

#### 2.시간차가 0일인 사용자를 제외하고, 나머지 사용자들의 평균 시간 각격(일 단위)을 계산하시오.

In [49]:
cond = order_df['시간간격'] > 0
order_df = order_df[cond]

mean_interval = order_df['시간간격'].mean()
print("mean_interval :", mean_interval)

mean_interval : 167.69463087248323

#### 3.평균 시간 간격보다 긴 시간 간격을 가진 사용자의 수를 정수로 구하시오.

In [50]:
cond = order_df['시간간격'] > mean_interval
print("사용자 수 :", sum(cond))

사용자 수 : 146

## S26.날짜와 시간 정보 변환, 비율

In [3]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.주문이 가장 많이 발생한 연-월을 찾으시오.

In [6]:
df['주문연월'] = df['주문시간'].dt.to_period('M')

order_max = df['주문연월'].value_counts().idxmax()
order_count= df['주문연월'].value_counts().max()

print("최대 주문발생 연월 :", order_max)
print("최대 주문발생 건수 :", order_count)

최대 주문발생 연월 : 2022-09
최대 주문발생 건수 : 95

#### 2.해당 연-월에 '배고팡'앱을 통한 주문 중 '앱결제'로 결제된 주문의 비율을 계산하시오.
#### (반올림 후 소수 둘째 자리까지 계산)

In [12]:
cond1 = df['주문연월'] == order_max
cond2 = df['앱종류'] == '배고팡'

filtered_df = df[cond1 & cond2]

filtered_df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,주문연월
38,2022-09-11 05:12:02,2022-09-11 06:02:35,2022-09-11 05:42:50,배고팡,17.10,현금,user_430,2022-09
76,2022-09-07 03:05:02,2022-09-07 03:48:11,2022-09-07 04:07:53,배고팡,1.10,앱결제,user_401,2022-09
98,2022-09-01 03:23:11,2022-09-01 04:03:16,2022-09-01 03:47:38,배고팡,4.28,현금,user_472,2022-09
127,2022-09-10 10:13:46,2022-09-10 11:27:34,2022-09-10 10:52:38,배고팡,10.95,현금,user_125,2022-09
133,2022-09-26 08:50:25,2022-09-26 10:16:55,2022-09-26 09:17:49,배고팡,19.60,카드,user_133,2022-09

In [14]:
cond = filtered_df['결제종류'] == '앱결제'
result = sum(cond) / len(filtered_df)

print("앱결제 비율 :", round(result,2))

앱결제 비율 : 0.31

## S27.시간 범위, 속도(km/h)

In [24]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.점심시간(10시부터 13시 전까지)에 주문된 배달 데이터를 찾으시오.

In [25]:
df['시간'] = df['주문시간'].dt.hour
df.head()

cond = df['시간'].between(10,13, inclusive='left')
print("점심시간 주문건수 :", sum(cond))

df = df[cond]
df.head()

점심시간 주문건수 : 120

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,시간
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,10
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,10
7,2023-01-19 11:32:02,2023-01-19 13:10:13,2023-01-19 13:24:54,여기여,10.04,카드,user_337,11
18,2023-02-03 11:08:34,2023-02-03 12:08:07,2023-02-03 11:44:14,여기여,18.21,현금,user_198,11
22,2022-11-03 10:05:17,2022-11-03 11:25:32,2022-11-03 10:52:13,배달왕,4.25,카드,user_204,10

#### 2.점심시간 주문 건 중 과속(평균 속도가 50km/h 이상)하는 주문 수를 정수로 구하시오.
#### 배달시간=실제도착시간 - 주문시간
#### 속도(km/h)=거리(km)/시간(h)

In [26]:
df['배달시간'] = df['실제도착시간'] - df['주문시간']
df['배달시간'] = df['배달시간'].dt.total_seconds()/60/60
df['속도'] = df['거리']/df['배달시간']

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,시간,배달시간,속도
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,10,0.369444,14.048120
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,10,0.499167,21.836394
7,2023-01-19 11:32:02,2023-01-19 13:10:13,2023-01-19 13:24:54,여기여,10.04,카드,user_337,11,1.636389,6.135461
18,2023-02-03 11:08:34,2023-02-03 12:08:07,2023-02-03 11:44:14,여기여,18.21,현금,user_198,11,0.992500,18.347607
22,2022-11-03 10:05:17,2022-11-03 11:25:32,2022-11-03 10:52:13,배달왕,4.25,카드,user_204,10,1.337500,3.177570

In [27]:
cond = df['속도'] >= 50
print('과속 건수 :', sum(cond))

과속 건수 : 1

## S28.날짜와 시간, 문자열

In [30]:
df = pd.read_csv('delivery_time.csv')

df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.연도와 월을 기준으로 주문 수를 집계하시오.

In [31]:
df['주문연월'] = df['주문시간'].dt.to_period('M')
order = df['주문연월'].value_counts()
order

주문연월
2022-09    95
2022-12    94
2023-04    88
2023-06    86
2023-07    83
2023-05    83
2023-01    82
2022-11    81
2022-10    79
2023-03    73
2023-02    70
2023-08    57
2022-08    29
Freq: M, Name: count, dtype: int64

#### 2.가장 많은 주문이 있었던 연도와 월을 예시와 같은 형식으로 숫자로만 구하시오.
#### (예 : 2024년 2월인 경우 '202402', 2024년 10월인 경우 '202410')

In [33]:
idxmax = order.idxmax()
print("가장 주문이 많은 연월형식 : ", str(idxmax).replace("-",""))

가장 주문이 많은 연월형식 :  202209

## S29.함수, 월별 집계

In [34]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.배달료 계산 기준표에 따라 각 주문에 대한 배달료를 계산하시오.
##### 5km 미만 : 2000원
##### 5km 이상 ~ 10km 미만 : 4000원
##### 10km 이상 ~ 15km 미만 : 6000원
##### 15km 이상 ~ 20km 미만 : 8000원

In [35]:
def delivery_fee(distance):
    result = 0
    if distance < 5:
        result = 2000
    elif distance < 10:
        result = 4000
    elif distance < 15:
        result = 6000
    elif distance < 20:
        result = 8000
    return result

In [36]:
df['배달료'] = df['거리'].apply(delivery_fee)
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,배달료
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275,2000
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,4000
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36,6000
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,6000
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176,6000

#### 2.연도-월별로 배달료의 총합을 집계하시오.

In [39]:
df['배달연월'] = df['주문시간'].dt.to_period('M')
sum_df = df.groupby(['배달연월'])['배달료'].sum()

sum_df

배달연월
2022-08    152000
2022-09    446000
2022-10    388000
2022-11    384000
2022-12    442000
2023-01    386000
2023-02    340000
2023-03    408000
2023-04    410000
2023-05    420000
2023-06    448000
2023-07    434000
2023-08    292000
Freq: M, Name: 배달료, dtype: int64

#### 3.배달료가 가장 많이 발생한 월을 찾고, 그 월의 총 배달료를 정수로 구하시오.

In [40]:
print("배달료가 가장 많이 발생한 월 :", sum_df.idxmax())
print("총배달료 :", sum_df.max())

배달료가 가장 많이 발생한 월 : 2023-06
총배달료 : 448000

## 주말, 평일구분

In [41]:
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'], format='%Y-%m-%d %H:%M:%S')
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'], format='%Y-%m-%d %H:%M:%S')
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'], format='%Y-%m-%d %H:%M:%S')

df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

#### 1.주말주문건수와 평일 주문 건수를 구하시오.

In [46]:
df['요일'] = df['주문시간'].dt.dayofweek
df['주말여부'] = df['요일'] >= 5

weekend = sum(df['주말여부'])
weekday = sum(~df['주말여부'])

print("평일 수  :", weekday)
print("주말 수  :", weekend)

평일 수  : 706
주말 수  : 294

#### 주말주문건수와 평일주문건수의 차이를 절대값으로 구하고 정수형으로 구하시오.

In [47]:
result = abs(weekday-weekend)
result = int(result)

print("결과 :", result)

결과 : 412